development:
  adapter: mysql2
  database: rails_cms_dev
  pool: 5
  timeout: 5000
  username: root
  password: asdf

test:
  adapter: mysql2
  database: rails_cms_test
  pool: 5
  timeout: 5000
  username: root
  password: asdf
